/* Simulation Wave: actual artwork first, grouped studies, same-origin downloads. */
const Simulation=(()=>{
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const order=['la-ola-de-amor','ola-collectibles','fpl-wave','gdb-wave','wave-26','simulation-wave','blockbuster-wave','ola-hq','willpwr-wave','wu-wei-wave','aios','our-polaroid-wave','offbrand-wave','capybara-wave'];
const profiles={
'simulation-wave':['Simulation Lab','WHAT IF?','Impossible objects, imagined places and happy accidents. Follow an idea wherever it goes.'],
'la-ola-de-amor':['La Ola de Amor','LOVE, IN EVERY FORM','A love story becoming its own world. Celebrations, signs, stages and the little things that carry it.'],
'wave-26':['Wave 26','IDEAS YOU CAN HEAR','Songs become images. Images become album worlds. Enter the music and visual experiments.'],
'gdb-wave':['GDB University','ENROLL IN THE GROOVE','A playful campus for bass, late nights and creative studies.'],
'ola-collectibles':['La Ola Collectibles','SMALL THINGS, WHOLE WORLDS','Cards, packs and the pleasure of collecting.'],
'fpl-wave':['La Ola FC','THE BEAUTIFUL EXPERIMENT','Football, fantasy and a club built from imagination. Kits, stadiums, crests and league stories.'],
'blockbuster-wave':['Blockbuster Wave','ROLL THE POSSIBILITY','Cinema through our lens. Poster worlds, scorecards and movie-night experiments.'],
'our-polaroid-wave':['Our Polaroid Wave','A MOMENT, HELD','Memory meets design. Imagined identities and objects for keeping a moment.'],
'wu-wei-wave':['Wu Wei Wave','FIND THE FLOW','Stillness, presence and room to breathe.'],
'willpwr-wave':['WILLPWR Wave','KEEP SHOWING UP','Discipline, movement and becoming.'],
'offbrand-wave':['Offbrand Wave','OFF THE EXPECTED PATH','An identity experiment with room to grow.'],
'capybara-wave':['Capybara Wave','A LITTLE CHAOS. A LOT OF CUTE.','A capybara, a wave and a world waiting to happen.'],
'ola-hq':['OLA HQ','MANY WAVES. ONE HOME.','Identity, culture and the visual threads that bring these projects together.'],
'aios':['AIOS','TOOLS FOR THE POSSIBLE','Ways to think, make and work with AI.']};
function parse(hash){const [path,q='']=(hash||'#/').replace(/^#/,'').split('?'),s=path.split('/').filter(Boolean),p=new URLSearchParams(q);return {kind:s[0]||'home',world:s[1]?decodeURIComponent(s[1]):'',project:p.get('project')||p.get('node')||'',filter:p.get('filter')||'',q:p.get('q')||'',page:Math.max(0,parseInt(p.get('page'),10)||0),linked:p.get('linked')==='1',focus:p.get('focus')||''};}
function hash(r){const p=new URLSearchParams();for(const k of ['project','filter','q','focus'])if(r[k])p.set(k,r[k]);if(r.page)p.set('page',r.page);if(r.linked)p.set('linked','1');return '#/'+(r.kind==='home'?'':r.kind+(r.world?'/'+encodeURIComponent(r.world):''))+(p.size?'?'+p:'');}
function model(d){const worlds=Object.fromEntries(d.worlds.map(w=>[w.id,w])),projects=Object.fromEntries(d.projects.map(p=>[p.id,p])),nodes=Object.fromEntries(d.nodes.map(n=>[n.id,n]));
function matches(a,r){if(r.kind==='project'||r.kind==='world'){if(r.linked){if(a.home===r.world||!a.connections.includes(r.world))return false;}else if(a.home!==r.world)return false;const n=nodes[r.filter||r.project];if(n&&!(a.wave===n.path||a.wave.startsWith(n.path+' / ')))return false;}return true;}
const search=Object.fromEntries(d.groups.map(g=>[g.id,(g.title+' '+g.assets.map(id=>{const a=d.assets[id];return a.title+' '+a.wave+' '+(profiles[a.home]?.[0]||a.home)}).join(' ')).toLowerCase()]));
function groups(r){const all=d.groups.filter(g=>g.assets.some(id=>matches(d.assets[id],r))&&(!r.q||search[g.id].includes(r.q.trim().toLowerCase())));if(r.focus)all.sort((a,b)=>(b.id===r.focus)-(a.id===r.focus));return all;}
return {worlds,projects,nodes,matches,groups};}
function sprite(i){if(i.uri)return {aspectRatio:i.w+'/'+i.h,backgroundImage:`url("${i.uri}")`,backgroundSize:'contain',backgroundPosition:'center'};return {aspectRatio:i.w+'/'+i.h,backgroundSize:(i.W/i.w*100)+'% '+(i.H/i.h*100)+'%',backgroundPosition:(i.W===i.w?0:i.x/(i.W-i.w)*100)+'% '+(i.H===i.h?0:i.y/(i.H-i.h)*100)+'%',backgroundImage:`url("${i.atlas}")`};}
return {E,order,profiles,parse,hash,model,sprite,PAGE_SIZE:36};
})();
if(typeof module!=='undefined'&&module.exports)module.exports=Simulation;
if(typeof document!=='undefined'){
(async()=>{
const {E,order,profiles,parse,hash,sprite,PAGE_SIZE}=Simulation,main=document.getElementById('main'),viewer=document.getElementById('viewer');
let data,M,current,previous='',visible=[],viewerGroup=null;const scrolls=new Map(),choices=new Map(),worldHistory=new Map(),imageCache=new Map();
const name=id=>profiles[id]?.[0]||M.worlds[id]?.name||'Project';
const link=r=>E(hash(r));
function nav(r){save();const h=hash(r);if(location.hash===h)render();else location.hash=h;}
function save(){if(previous)scrolls.set(previous,scrollY);if(current?.world)worldHistory.set(current.world,{...current});}
function searchBox(q='',hint='Search an idea, artwork or project…'){return `<form class="search-box" id="searchForm" role="search"><span aria-hidden="true">⌕</span><input id="searchInput" type="search" aria-label="${E(hint)}" placeholder="${E(hint)}" value="${E(q)}"><button aria-label="Search" type="submit">↗</button></form>`;}
function projectDesc(p){const s=(p.label+' '+p.path).toLowerCase();if(s.includes('memory object'))return 'Keepsake, souvenir and memory-object concepts — visual ideas for holding onto a moment.';if(s.includes('identity'))return 'Logos, marks, symbols and visual identity experiments for this world.';if(s.includes('places / objects'))return 'Objects, locations and imagined scenes — visual experiments without a larger project attached.';if(s.includes('portrait')||s.includes('character'))return 'Portrait and character experiments — faces, figures and visual personalities.';return '';}
function tile(title,cover,url,kicker,desc='',accent=''){return `<a class="tile" href="${url}" style="--accent:${E(accent||'#ff9ad7')}"><div class="cover"><img src="${E(cover)}" alt="${E(title)} — illustrated project entrance" loading="lazy" width="768" height="768"></div><div class="tile-body"><div class="tile-kicker">${E(kicker)}<span>EXPLORE</span></div><h3 class="tile-title">${E(title)}<span class="arrow" aria-hidden="true">↗</span></h3>${desc?`<p class="tile-desc">${E(desc)}</p>`:''}</div></a>`;}
function home(){return `<section class="hero"><div><p class="eyebrow">A LITTLE IMAGINATION. A LOT OF POSSIBILITY.</p><h1>Come in.<br><em>Make waves.</em></h1><p class="lead">Ideas become artwork. Artwork becomes worlds.<br>With AI at our fingertips, there’s always another way to see it.</p><div class="hero-actions"><a class="primary" href="#projects" data-explore>Explore the projects <span aria-hidden="true">↗</span></a><button class="secondary" data-surprise>Surprise me <span aria-hidden="true">✧</span></button></div><p class="badge-note">Made with curiosity. Connected by OLA.</p></div><div class="hero-art"><img src="assets/covers/hero.webp" alt="An impossible colorful glass wave flows through a glowing portal" fetchpriority="high" width="1200" height="1200"><span class="orbit-note">EVERY IDEA HAS A WORLD INSIDE IT</span></div></section><section id="projects"><div class="section-bar"><div><p class="eyebrow">PICK A DIRECTION</p><h2>All the projects. All connected.</h2><p>Go in, look around, float somewhere new.</p></div>${searchBox()}</div><div class="grid">${order.filter(id=>M.worlds[id]).map(id=>tile(name(id),M.worlds[id].cover,link(worldHistory.get(id)||{kind:'project',world:id}),'A WORLD OF POSSIBILITIES',profiles[id][2],M.worlds[id].color)).join('')}</div></section>`;}
function titles(g,index){const raw=g.title.replace(/\.(png|jpg|jpeg|webp|svg)$/i,'').replace(/_/g,' ');if(/^(generated.image|ChatGPT Image|image[- ]?\d|s[- ]?[0-9a-f]{12})/i.test(raw)||raw.length>110){const a=data.assets[g.assets[0]],path=a.wave.split(' / '),p=data.projects.find(x=>x.world===a.home&&(a.wave===x.path||a.wave.startsWith(x.path+' / ')));return (path.length>1?path.at(-1):p?.label||path.at(-1)||'Visual study')+' · '+String(index+1).padStart(2,'0');}return raw;}
function card(g,index){const ids=g.assets.filter(id=>M.matches(data.assets[id],current));let pick=choices.get(g.id)||0;if(pick>=ids.length)pick=0;choices.set(g.id,pick);g._visible=ids;return `<article class="art-card" data-group="${E(g.id)}"><div class="art-window"><button class="art-inspect" data-inspect="${E(g.id)}" aria-label="Enlarge ${E(titles(g,index))}"><span class="actual-art" role="img" aria-label="${E(titles(g,index))}" data-image="${E(ids[pick])}"></span></button>${ids.length>1?`<button class="carousel prev" data-step="-1" aria-label="Previous variation of ${E(titles(g,index))}">‹</button><button class="carousel next" data-step="1" aria-label="Next variation of ${E(titles(g,index))}">›</button>`:''}</div><div class="art-caption"><div><h3>${E(titles(g,index))}</h3><p class="variation-label" aria-live="polite">${ids.length>1?'Study '+(pick+1)+' / '+ids.length:name(data.assets[ids[pick]].home)}</p></div><button class="download" data-download="${E(g.id)}" aria-label="Download displayed artwork: ${E(titles(g,index))}" title="Download displayed artwork">↓</button></div></article>`;}
function gallery(r){const all=M.groups(r),pages=Math.max(1,Math.ceil(all.length/PAGE_SIZE));r.page=Math.min(r.page,pages-1);visible=all.slice(r.page*PAGE_SIZE,(r.page+1)*PAGE_SIZE);return `<div class="gallery-heading"><div><h2>${r.q?'Following “'+E(r.q)+'”':r.linked?'Floating in from other worlds':'The artwork, together'}</h2><p>Every idea is already open. Swipe or use the arrows to explore its studies.</p></div>${searchBox(r.q,r.world?'Search within '+name(r.world)+'…':'Search the artwork…')}</div><div class="art-grid">${visible.length?visible.map((g,i)=>card(g,r.page*PAGE_SIZE+i)).join(''):'<div class="empty"><h2>Let’s catch another wave.</h2><p>No artwork matched this search.</p><button class="secondary" data-clear>Clear the search</button></div>'}</div>${pages>1?`<div class="pagination"><button data-page="${r.page-1}" ${r.page===0?'disabled':''}>← Previous</button><span>Page ${r.page+1} of ${pages}</span><button data-page="${r.page+1}" ${r.page===pages-1?'disabled':''}>Next →</button></div>`:''}`;}
function world(r){const w=M.worlds[r.world];if(!w)return missing();const p=M.projects[r.project];if(r.project&&(!p||p.world!==r.world))r.project='';const projects=data.projects.filter(x=>x.world===r.world);const connected=M.groups({kind:'project',world:r.world,linked:true}).length;const back=p?{kind:'project',world:r.world}:{kind:'home'};let html=`<div class="project-view" style="--accent:${E(w.color)}"><div class="breadcrumbs"><a href="#/">All projects</a><span>/</span><a href="${link({kind:'project',world:r.world})}">${E(name(r.world))}</a>${p?'<span>/</span><span class="crumb-current">'+E(p.label)+'</span>':''}</div><div class="compact-intro"><div><p class="eyebrow">${E(p?name(r.world):profiles[r.world][1])}</p><h1>${E(p?.label||name(r.world))}</h1>${!p?'<p class="intro-desc">'+E(profiles[r.world][2])+'</p>':''}<a class="back-link" href="${link(back)}">← Back to ${E(p?name(r.world):'all projects')}</a></div><img src="${E(p?.cover||w.cover)}" alt="${E(p?.label||name(r.world))} project illustration" width="128" height="128"></div>`;
if(!p&&projects.length&&!r.q&&!r.linked){html+=`<section class="project-doors"><div class="section-bar"><div><h2>Find your next wave.</h2><p>Pick a project. Its artwork is waiting inside.</p></div><a class="small-button" href="#artworks" data-scroll-art>Surf all artwork ↓</a></div><div class="grid">${projects.map(x=>tile(x.label,x.cover,link({...r,project:x.id,page:0,filter:'',linked:false,q:''}),'EXPLORE THE PROJECT',projectDesc(x),w.color)).join('')}</div></section>`;}
if(p){const filters=data.nodes.filter(n=>n.parent===p.id&&data.assets&&Object.values(data.assets).some(a=>a.home===r.world&&(a.wave===n.path||a.wave.startsWith(n.path+' / '))));if(filters.length>1)html+=`<div class="controls filters" aria-label="Filter artwork"><a class="pill ${!r.filter?'selected':''}" href="${link({...r,filter:'',page:0})}">All studies</a>${filters.map(n=>`<a class="pill ${r.filter===n.id?'selected':''}" href="${link({...r,filter:n.id,page:0})}">${E(n.label)}</a>`).join('')}</div>`;}
html+=`<section id="artworks">${gallery(r)}</section>`;
if(connected&&!p)html+=`<div class="connected-banner"><div><strong>These worlds float together.</strong><p>Follow the creative threads into other projects.</p></div><a class="small-button" href="${link({...r,linked:!r.linked,page:0,project:'',filter:''})}">${r.linked?'Return to this world':'Follow the connections'} ↗</a></div>`;
if(p&&projects.length>1)html+=`<details class="other-projects"><summary>Surf another project in ${E(name(r.world))}</summary><div class="grid">${projects.filter(x=>x.id!==p.id).map(x=>tile(x.label,x.cover,link({...r,project:x.id,filter:'',page:0,q:''}),'KEEP EXPLORING')).join('')}</div></details>`;return html+'</div>';}
function missing(){return '<div class="empty"><h1>Let’s catch another wave.</h1><a class="primary" href="#/">Back to all projects ↗</a></div>';}
let observer;function paint(el,id){const a=data.assets[id];if(!a)return;const styles=sprite(a.image);Object.assign(el.style,styles);el.style.setProperty('--natural-ratio',a.image.w&&a.image.h?a.image.w/a.image.h:1);el.dataset.image=id;el.classList.add('art-loaded');}
function loadArt(){observer?.disconnect();observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){paint(e.target,e.target.dataset.image);observer.unobserve(e.target);}}, {rootMargin:'600px'});main.querySelectorAll('.actual-art').forEach(el=>observer.observe(el));}
function selected(g){return data.assets[g._visible[choices.get(g.id)||0]];}
function step(id,delta){const g=visible.find(g=>g.id===id)||viewerGroup;if(!g||g._visible.length<2)return;const index=((choices.get(id)||0)+delta+g._visible.length)%g._visible.length;choices.set(id,index);const card=main.querySelector(`[data-group="${id}"]`);if(card){paint(card.querySelector('.actual-art'),g._visible[index]);card.querySelector('.variation-label').textContent=`Study ${index+1} / ${g._visible.length}`;}if(viewer.open&&viewerGroup?.id===id)showViewer(g);}
function showViewer(g){viewerGroup=g;const a=selected(g);document.getElementById('viewerArt').innerHTML='<div class="actual-art"></div>';paint(document.querySelector('#viewerArt .actual-art'),a.id);document.getElementById('viewerControls').innerHTML=`<button data-view-step="-1" ${g._visible.length<2?'hidden':''} aria-label="Previous variation">←</button><span>Study ${(choices.get(g.id)||0)+1} / ${g._visible.length}</span><button data-view-step="1" ${g._visible.length<2?'hidden':''} aria-label="Next variation">→</button><button data-view-download>Download ↓</button>`;viewer.querySelectorAll('[data-view-step]').forEach(b=>b.onclick=()=>step(g.id,Number(b.dataset.viewStep)));viewer.querySelector('[data-view-download]').onclick=()=>download(g);if(!viewer.open)viewer.showModal();}
async function imageFor(uri){if(!imageCache.has(uri))imageCache.set(uri,new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(new Error('Image could not load'));i.src=uri;}));return imageCache.get(uri);}
async function download(g){const a=selected(g),i=a.image,b=main.querySelector(`[data-download="${g.id}"]`)||viewer.querySelector('[data-view-download]');const label=b?.textContent;if(b){b.disabled=true;b.textContent='…';}try{const img=await imageFor(i.uri||i.atlas),canvas=document.createElement('canvas');canvas.width=i.w||img.naturalWidth;canvas.height=i.h||img.naturalHeight;const ctx=canvas.getContext('2d');if(i.uri)ctx.drawImage(img,0,0);else ctx.drawImage(img,i.x,i.y,i.w,i.h,0,0,i.w,i.h);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw new Error('Could not prepare image');const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=(g.title.replace(/\.(png|jpg|jpeg|webp|svg)$/i,'').replace(/[^a-z0-9 -]/gi,'').slice(0,70)||'Simulation-Wave')+'-study-'+((choices.get(g.id)||0)+1)+'.png';link.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}catch{if(b){b.textContent='Retry';b.title='Download could not be prepared. Try again.';}return;}finally{if(b){b.disabled=false;if(b.textContent!=='Retry')b.textContent=label;}}}
function wire(){const form=document.getElementById('searchForm');if(form)form.onsubmit=e=>{e.preventDefault();nav({...current,kind:current.world?'project':'artwork',q:document.getElementById('searchInput').value.trim(),page:0});};main.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>step(b.closest('[data-group]').dataset.group,Number(b.dataset.step)));main.querySelectorAll('[data-inspect]').forEach(b=>b.onclick=()=>showViewer(visible.find(g=>g.id===b.dataset.inspect)));main.querySelectorAll('[data-download]').forEach(b=>b.onclick=()=>download(visible.find(g=>g.id===b.dataset.download)));main.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>nav({...current,page:Number(b.dataset.page)}));main.querySelectorAll('[data-clear]').forEach(b=>b.onclick=()=>nav({...current,q:'',page:0}));main.querySelectorAll('[data-explore],[data-scroll-art]').forEach(b=>b.onclick=e=>{e.preventDefault();document.getElementById(b.hasAttribute('data-explore')?'projects':'artworks').scrollIntoView({behavior:'smooth'});});const surprise=main.querySelector('[data-surprise]');if(surprise)surprise.onclick=()=>{const g=data.groups[Math.floor(Math.random()*data.groups.length)],a=data.assets[g.assets[0]],p=data.projects.find(p=>p.world===a.home&&(a.wave===p.path||a.wave.startsWith(p.path+' / ')));nav({kind:'project',world:a.home,project:p?.id||'',focus:g.id});};main.querySelectorAll('.art-window').forEach(el=>{let x,y;el.addEventListener('touchstart',e=>{x=e.changedTouches[0].clientX;y=e.changedTouches[0].clientY;},{passive:true});el.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-x,dy=e.changedTouches[0].clientY-y;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.2){step(el.closest('[data-group]').dataset.group,dx<0?1:-1);el._swiped=true;setTimeout(()=>el._swiped=false,400);}},{passive:true});el.addEventListener('click',e=>{if(el._swiped){e.stopPropagation();e.preventDefault();}},true);});loadArt();}
function render(){save();current=parse(location.hash);if(current.kind==='world')current.kind='project';const title=current.world?(M.projects[current.project]?.label||name(current.world)):'Simulation Wave';document.title=title+' — Simulation Wave';visible=[];main.innerHTML=current.kind==='home'?home():current.kind==='project'?world(current):current.kind==='artwork'?'<div class="back-row"><a class="back-link" href="#/">← Back to all projects</a></div><div class="compact-intro"><div><p class="eyebrow">THE CONNECTED COLLECTION</p><h1>Every idea, in one place.</h1></div></div>'+gallery(current):missing();previous=location.hash||'#/';document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===(current.kind==='artwork'?'artwork':'home')));wire();requestAnimationFrame(()=>scrollTo(0,scrolls.get(previous)||0));}
viewer.querySelector('.viewer-close').onclick=()=>viewer.close();viewer.onclick=e=>{if(e.target===viewer)viewer.close();};viewer.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();step(viewerGroup.id,1);}if(e.key==='ArrowLeft'){e.preventDefault();step(viewerGroup.id,-1);}});addEventListener('scroll',()=>{if(previous)scrolls.set(previous,scrollY);},{passive:true});
try{data=window.SIMULATION_DATA||await fetch('catalog.json?v=2').then(r=>{if(!r.ok)throw new Error('Catalog unavailable');return r.json();});M=Simulation.model(data);addEventListener('hashchange',render);render();}catch{main.innerHTML='<div class="empty"><h1>The wave is taking a moment.</h1><p>Reload to reopen the gallery.</p><button class="primary" onclick="location.reload()">Reload ↗</button></div>';}
})();}
