const BASE=new URL('./',self.location.href);
const PREFIX='la-ola-guide-'+BASE.pathname+'-';
const CACHE=PREFIX+'v3-20261008-mobile-review-01';
const CORE=["../../assets/navigation-arrows.js", "./", "index.html", "guide/", "guide/index.html", "guide/guide.css", "guide/guide.js", "manifest.webmanifest", "../assets/heart-transparent.png", "guide/art/artist-01.webp", "guide/art/artist-02.webp", "guide/art/artist-03.webp", "guide/art/artist-04.webp", "guide/art/artist-05.webp", "guide/art/artist-06.webp", "guide/art/food-clean-01.webp", "guide/art/food-clean-02.webp", "guide/art/food-clean-03.webp", "guide/art/food-clean-04.webp", "guide/art/food-clean-05.webp", "guide/art/food-clean-06.webp", "guide/art/food-clean-07.webp", "guide/art/food-clean-08.webp", "guide/art/header-04.webp", "guide/art/header-05.webp", "guide/art/header-06.webp", "guide/art/header-07.webp", "guide/art/header-12.webp", "guide/art/identity-01.webp", "guide/art/identity-02.webp", "guide/art/identity-03.webp", "guide/art/identity-04.webp", "guide/art/identity-05.webp", "guide/art/identity-06.webp", "guide/art/identity-07.webp", "guide/art/identity-08.webp", "guide/art/identity-09.webp", "guide/art/identity-10.webp", "guide/art/identity-11.webp", "guide/art/identity-12.webp", "guide/art/identity-13.webp", "guide/art/identity-14.webp", "guide/art/identity-15.webp", "guide/art/legacy-walls-v34.webp", "guide/art/page-09.webp", "guide/art/la-ola-track-01.png", "guide/art/page-01.webp", "guide/art/page-02.webp", "guide/art/page-03.webp", "guide/art/page-04.webp", "guide/art/page-05.webp", "guide/art/page-06.webp", "guide/art/page-07.webp", "guide/art/page-08.webp", "guide/art/page-12.webp", "guide/art/page-15.webp", "guide/art/shug-shugy.webp", "guide/art/timeline-01.webp", "guide/art/timeline-02.webp", "guide/art/timeline-03.webp", "guide/art/timeline-04.webp", "guide/art/timeline-05.webp", "guide/art/timeline-06.webp", "guide/art/timeline-07.webp", "guide/art/timeline-08.webp", "guide/art/timeline-09.webp", "guide/art/timeline-10.webp", "guide/art/timeline-11.webp", "guide/art/timeline-12.webp"].map(path=>new URL(path,BASE).href);
const ALLOWED=new Set(CORE);
const ESSENTIAL=CORE.filter(url=>!url.includes('/art/')&&!url.endsWith('/assets/heart-transparent.png'));
const OPTIONAL=CORE.filter(url=>!ESSENTIAL.includes(url));
const LANGUAGES=new Map();
async function saveAsset(cache,url){const abort=new AbortController();const timer=setTimeout(()=>abort.abort(),12000);try{const response=await fetch(url,{cache:'reload',signal:abort.signal});if(!response.ok||response.type==='opaque')throw new Error('Asset unavailable');await cache.put(url,response);return true;}catch{return false;}finally{clearTimeout(timer);}}
async function statusFor(client){const cache=await caches.open(CACHE);const missing=(await Promise.all(CORE.map(async url=>(await cache.match(url))?null:url))).filter(Boolean);client?.postMessage({type:'CACHE_STATUS',shellReady:!ESSENTIAL.some(url=>missing.includes(url)),missing:missing.length});}
async function retryAssets(){const cache=await caches.open(CACHE);await Promise.all(OPTIONAL.map(async url=>{if(!await cache.match(url))await saveAsset(cache,url);}));}
self.addEventListener('install',event=>event.waitUntil((async()=>{const cache=await caches.open(CACHE);const saved=await Promise.all(ESSENTIAL.map(url=>saveAsset(cache,url)));if(saved.includes(false))throw new Error('Guide shell unavailable');await retryAssets();})()));
self.addEventListener('message',event=>{if(event.data?.lang==='en'||event.data?.lang==='es')LANGUAGES.set(event.source?.id,event.data.lang);if(event.data?.type==='APPLY_UPDATE')event.waitUntil(self.skipWaiting());if(event.data?.type==='CACHE_STATUS')event.waitUntil(statusFor(event.source));if(event.data?.type==='RETRY_ASSETS')event.waitUntil(retryAssets().then(()=>statusFor(event.source)));});
self.addEventListener('activate',event=>event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(key=>(key.startsWith(PREFIX)&&key!==CACHE)||key==='la-ola-festival-app-v1').map(key=>caches.delete(key)));await self.clients.claim();const clients=await self.clients.matchAll();await Promise.all(clients.map(statusFor));})()));
self.addEventListener('fetch',event=>{
 if(event.request.method!=='GET')return;
 const url=new URL(event.request.url),requested=new URL(event.request.url);
 if(url.origin!==BASE.origin)return;
 url.search='';url.hash='';if(!ALLOWED.has(url.href))return;
 event.respondWith((async()=>{const cache=await caches.open(CACHE);const hit=await cache.match(url.href);if(hit)return hit;
  try{const response=await fetch(event.request);if(response.ok&&response.type!=='opaque')await cache.put(url.href,response.clone());return response;}
  catch{const spanish=(requested.searchParams.get('lang')||LANGUAGES.get(event.clientId))==='es';const title=spanish?'Guía sin conexión':'Offline guide';const body=spanish?'No pudimos abrir esta página sin conexión.':'We could not open this page offline.';const back=spanish?'Volver a la guía':'Back to the guide';return new Response(event.request.mode==='navigate'?`<!doctype html><html lang="${spanish?'es-MX':'en'}"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><p>${body}</p><a href="${BASE.pathname}guide/?lang=${spanish?'es':'en'}">${back}</a></html>`:'Artwork unavailable offline',{status:503,headers:{'Content-Type':event.request.mode==='navigate'?'text/html; charset=utf-8':'text/plain; charset=utf-8'}});}
 })());
});
